name: CD Example Production

on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    name: CD Example Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: SHH Connect 
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "Berhasil Koneksi ke server"
            if [ -d "/home/rhystalgie" ]; then
              echo "Direktori /home/rhystalgie ada"
              cd /home/rhystalgie
              echo "Berhasil masuk ke direktori /home/rhystalgie"
            else
              echo "Direktori /home/rhystalgie tidak ada, membuat direktori..."
              mkdir /home/rhystalgie
              cd /home/rhystalgie
            fi

            if [ -d ".git" ]; then
              echo "Direktori .git ada, melakukan pull..."
              git remote set-url origin https://github.com/Rhystall/cicd_database
              git pull origin main
            else
              echo "Direktori .git tidak ada, melakukan clone..."
              git clone https://github.com/Rhystall/cicd_database .
            fi
