name: CICD Database Dev to Prod

on:
  push:
    branches:
      - main

jobs:
  db_cicd:
    name: Database CI/CD 
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v4
    
      # Step 2: SSH Connection to Server
      - name: SSH Connect 
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "✅ Berhasil Koneksi ke server"
            cd /home/rhystalgie/cicd_database
            echo "✅ Berhasil masuk ke direktori /home/rhystalgie/cicd_database"

            # Jalankan Docker Compose
            echo "🚀 Menjalankan docker compose..."
            echo "$PASSWORD" | sudo -S docker compose up -d

            # CI - Continuous Integration
            echo "⏳ Menunggu Server MySQL Siap (30 detik)"
            sleep 30

            # Cek Database di mysql_devel_container
            echo "🛠️ Menampilkan database di mysql_devel_container"
            sudo docker exec mysql_devel_container mysql -u root -pTelkom123! -e "SHOW DATABASES;"

            # CD - Continuous Deployment
            echo "📦 DUMP Database dari mysql_devel"
            sudo docker exec mysql_devel_container sh -c "mysqldump -u root -pTelkom123! academics_devel" > dump.sql

            # Cek jika dump.sql berhasil dibuat
            if [ -f dump.sql ]; then
              echo "✅ Dump berhasil dibuat"
            else
              echo "❌ Dump gagal dibuat"
              exit 1
            fi

            # Copy dump.sql ke mysql_prod_container
            echo "📦 Copy dump.sql ke mysql_prod_container"
            sudo docker cp dump.sql mysql_prod_container:/tmp/dump.sql

            # Import dump.sql ke mysql_prod_container
            echo "📦 Import dump.sql ke mysql_prod_container"
            sudo docker exec mysql_prod_container sh -c "mysql -u root -pTelkom123! academics < /tmp/dump.sql"

            echo "✅ Berhasil Import Database ke mysql_prod"
