name: CICD Database Dev to Prod

on:
  push:
    branches:
      - main


jobs:
  db_cicd:
    name: Database CI/CD 
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v4 #Checkout ke repository kita cik 
    
    - name: SSH Connect 
      uses: appleboy/ssh-action@v1.2.2
      with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: [
            'echo "Berhasil Koneksi ke server"',
          ]







