name: CICD Database Dev to Prod

on:
  push:
    branches:
      - main

jobs:
  db_cicd:
    name: Database CI/CD 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: SSH Connect 
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Berhasil Koneksi ke server"
            cd /home/rhystalgie/cicd_database
            echo "Berhasil masuk ke direktori /home/rhystalgie/cicd_database"
            sudo docker compose up -d
            echo "Berhasil menjalankan docker compose"


            echo "Menunggu mysql untuk siap..."
            sleep 30

            docker exec mysql_devel_container mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "SHOW_DATABASES;" #Menampilkan database yang ada di mysql_devel_container
